### PR TITLE
Add Test to replicate issue #4621

### PR DESCRIPTION
**Pull request by nebojsasandin**
Modified Google test to replicate this issue: https://github.com/cefsharp/CefSharp/issues/4621

### CODE REVIEW

**Comment by amaitland** [comment]
- Please fix the formatting (you've reformatted the whole file). 
- Please create a new test for the issue rather than rewriting an existing one (we still need to keep the existing one).

> [Add files via upload](https://github.com/cefsharp/CefSharp/pull/4741/commits/aa9497109a6cd82083cc55805cb15fe3e3accd8d)

It appears you've uploaded the file which makes me wonder if you've actually run the test?

**Comment by nebojsasandin** [comment]
@amaitland 
Is it better now?
- Previously you've given me a direct line to a Google test method, made me think you wanted me to include this Google-related issue into that test. Forgive my foolishness.
- I have created a new test, and ran it, it still produces the same issue previously stated.
- Originally I could not run any tests on my end, when I compiled the code I got a whole bunch of C++ errors I'm unfamiliar with, and I could not work out how to make it run, so I just changed the test I needed to. Then I got error 403 - Forbidden when I tried to commit from my computer, so I simply uploaded the file via git web. I did not think it would mess up the entire file formatting. Sorry about that. Desktop git is working now, and the entire source is compiling properly, so I was able to do both: run the test locally, and commit changes properly.
- Let me know if there's anything else you need from me.

**Comment by amaitland** [comment]
Thanks. I'll have a look closer on the weekend.

**Comment by amaitland** [comment]
The issue does indeed look like an `upstream` one. If you isolate the two origins in different render processes then it should work as expected.

```c#
settings.CefCommandLineArgs.Add("isolate-origins", "https://www.google.com,https://accounts.google.com/");
```

**Comment by amaitland** [comment]
I've manually merged this test in commit https://github.com/cefsharp/CefSharp/commit/800cbcf0fd58d85bfa0c3f57636ddfa823a1b830

It's now in a separate file that references the original issue.

Thanks for the unit tests 👍

**Pull request closed without merging**
