### PR TITLE
Nuget - Update targets to use <ContentWithTargetPath/>

### LINKED ISSUE #2456: Hide artifacts from VS Solution Explorer in new CsProj format
- **What version of the product are you using?**
CefSharp.OffScreen 65.0.0 from nuget

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen

- **What steps will reproduce the problem?**
Create a new .net core console app, or even a .net framework app but using the new CsProj format

- **What is the expected output? What do you see instead?**
Solution explorer in VS 2017 15.7.5 is showing all the CefSharp artifacts (see below)

- **Please provide any additional information below.**
image

I've been trying various versions of the hacks listed here: https://github.com/NuGet/Home/issues/4856#issuecomment-404716672 to no avail.  Any idea how to hide these artifacts from view?

### PR DESCRIPTION
**Pull request by DaZiYuan**
replace None with ContentWithTargetPath

Fixes #2456 

**Summary:** [summary of the change and which issue is fixed here]
- modify “None” to  "ContentWithTargetPath" in nuget floder

**Changes:** 
- modify CefSharp.Common.targets
- modify CefSharp.WinForms.targets
- modify CefSharp.Wpf.targets
- add winform/wpf .targets file to nuget folder
      
## Screenshots (if appropriate):
before change:
image
after change:
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated documentation

**Checklist:**
- [ ] Tested the code(if applicable)
- [ ] Commented my code
- [ ] Changed the documentation(if applicable)
- [ ] New files have a license disclaimer
- [ ] The formatting is consistent with the project (project supports .editorconfig)

### CODE REVIEW

**Comment by amaitland** [comment]
Please provide a reference that details `<ContentWithTargetPath/>`.

We still support `VS2013/2015/2017`, so any change needs to be backwards compatible.

The `<None/>` entries copy the files one level deep when referenced as a sub project (you can reference `CefSharp` in a dll and the relevant folders will be copied to your executable long as it's a direct reference). Please evaluate if this change in a breaking one in this context.

**Comment by DaZiYuan** [comment]
image

vs2015 looks fine ,I don't have vs2013/17.  I will be grateful if somebody can help this .

**Comment by amaitland** [comment]
Without a clear understanding of `ContentWithTargetPath`, what versions it supports, does it include the resource in a `ClickOnce` installer like changing to `<Content/>` would I cannot proceed with this. Appreciate the effort though 👍 

For me the safest option would be changing to `<Content/>` as outlined in https://github.com/cefsharp/CefSharp/issues/2456#issuecomment-405543385

**Comment by amaitland** [comment]
A new set of packages that better supports `PackageReferene` will be created see #2795 for details.

**Pull request closed without merging**
