### PR TITLE
WPF - Change PixelFormat from Bgra32 to Pbgra32 to fix control transparency

### LINKED ISSUE #2127: WPF - Transparency Rendering Too Dark
- **What version of the product are you using?**
    - CefSharp.Common / CefSharp.Wpf v57.0.0

- **What architecture x86 or x64?**
   - Either / Both

- **On what operating system?**
    - Windows 10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - WPF

- **What steps will reproduce the problem?**
    - Set a white coloured background behind the control
    - Enable OffScreenTransparentBackground
    - Navigate to a page with a 50% white background (body background: rgba(255,255,255,0.5), html background: transparent)

- **What is the expected output? What do you see instead?**
   - Background is gray rather than white.

- **Please provide any additional information below.**
    - No exceptions or error messages occur.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    - No, but likely doesn't use transparent background.

### PR DESCRIPTION
**Pull request by maloshuk**
Resolves #2127

When making CefSharp.WPF control semi-transparent and show it above another window, the control is darken. That happens because of incorrect interpretation of pixel data format received from cef.  Cef provides pixel data with premultiplied alpha (PixelFormats.Pbgra32 in .NET), while CefSharp.WPF treated them as having straight alpha (PixelFormats.Bgra32). 

The same issue was experienced in CEF delopment. 
https://bitbucket.org/chromiumembedded/cef/issues/584
Wich leaded to Skia and statement that it provides pixel data with premultiplied alpha. https://bugs.chromium.org/p/skia/issues/detail?id=547.

### CODE REVIEW

**Comment by merceyz** [comment]
Shouldn't the other rendering methods be updated as well?

**Comment by amaitland** [comment]
> That happens because of incorrect interpretation of pixel data format received from cef. Cef provides pixel data with premultiplied alpha (PixelFormats.Pbgra32 in .NET), while CefSharp.WPF treated them as having straight alpha (PixelFormats.Bgra32).

@maloshuk Excellent, thanks 👍 

> Shouldn't the other rendering methods be updated as well?

I believe there are six instances that require updating.

**Comment by maloshuk** [comment]
> > Shouldn't the other rendering methods be updated as well?
> 
> I believe there are six instances that require updating.

Yes,  'Find all references' gives 5 more places where PixelFormats.Bgra32 is in use. But I do not know code that good to edit all of them in blind. I will find time to fix them too. 
Thanks for support. You doing great product.

**Comment by amaitland** [comment]
> But I do not know code that good to edit all of them in blind

All instances should be changed :+1:

**Comment by maloshuk** [comment]
> All instances should be changed 👍

Ok. I changed them.

**Comment by amaitland** [comment]
Thanks

**Pull request merged**
