### PR TITLE
Added Drag Drop support to allow dragging objects into the browser (PR to master)

### PR DESCRIPTION
**Pull request by Bodekaer**
Hey @amaitland,

I had to re-create, as I could not change the branch.
I'll just compare with `master` in going forward.

### CODE REVIEW

**Comment by amaitland** [comment]
Has the `AppVeyor` green tick of approval again :smile:

**Comment by Bodekaer** [comment]
Ahh, feels much better :)

**Comment by amaitland** [comment]
@Bodekaer I've actioned the comments from the previous PR and merged this :smile:

**Comment by Bodekaer** [comment]
Awesome! You're the best :)
Been super busy lately preparing for our 2.0 launch, so just didn't get around to it yet.
You'll be happy to know that all your CefSharp code and work will soon be used by 10s of thousands more users every single day - all day :)

**Comment by amaitland** [comment]
> You'll be happy to know that all your CefSharp code and work will soon be used by 10s of thousands more users every single day - all day

Cool :smile:

**Pull request merged**
