### PR TITLE
Link Readme to Website

### PR DESCRIPTION
**Pull request by hgupta9**
I've simple linked the readme to the website & wiki.

### CODE REVIEW

**Comment by amaitland** [comment]
Is there a way to format the links so they look nicer? The `H2` makes them giant and doesn't look great.

**Comment by hgupta9** [comment]
I've made it smaller. Is it ok now?

https://github.com/hgupta9/CefSharp

**Comment by amaitland** [comment]
Still looks out of place IMHO.

**Comment by amaitland** [comment]
I think https://github.com/amaitland/CefSharp/commit/eabc3a861e53c417500ac85b1d26436436b90a64 looks slightly better, though not totally happy with it.

**Comment by hgupta9** [comment]
Taking inspiration from this: https://github.com/atom/electron

How is this? https://github.com/hgupta9/CefSharp

**Comment by amaitland** [comment]
Changes applied in #1477

I squashed your changes into a single commit. (I usually prefer small granular commits, in this case I think it's cleaner if there's just one).

**Comment by amaitland** [comment]
Thanks for the hard work :+1:

**Comment by amaitland** [comment]
> 3 version shields, all linked to nuget (is that ok or you just want one?)

I wonder if there's a way to include their name?

**Comment by hgupta9** [comment]
> Changes applied in #1477

That is very cool. 

> Thanks for the hard work

Sure, no problem. And you're welcome. A little "thanks" goes a long way. Especially since this is open source and "thanks" is the only "reward" you get!!

**Comment by amaitland** [comment]
> It happened that way because there is no MD preview (unlike SO), so I had to make multiple commits to get a feel of my changes.

There is a `Preview Changes` if you edit the file online using the web interface. 

> And if you can please look into merging PR6. Its mostly cosmetic improvements so don't need to "double check" anything much. cefsharp/cefsharp.github.io#6

Will look at it shortly :+1:

**Pull request closed without merging**
