### PR TITLE
Continued API Rewrite

### PR DESCRIPTION
**Pull request by amaitland**
Trying to reduce the code complexity a little bit. 

More changes to come.

### CODE REVIEW

**Comment by rassilon** [comment]
I was doing just that and I'm debugging a MCefRefPtr related garbage hitting the finalizer or indeed not at all and CEF assert during CEF.Shutdown.

Bill

**Comment by amaitland** [comment]
Merge this `PR` so you can remove `DisposableResource`?

**Comment by rassilon** [comment]
Sure.

**Comment by amaitland** [comment]
Done. Still quite a few cleanups to go. Will look at creating another `PR` later. Need to review all the callbacks, make sure weren't not disposing the wrappers too quickly for them to be used an an `async` fashion.

**Comment by rassilon** [comment]
The callbacks don't clean themselves up.  However, the fix for them looks
simple.

**Comment by amaitland** [comment]
I was thinking more along the lines of when you pass in a `CefFrameWrapper` instance, making sure that it can be accessed from within a `Task` when using a callback. I'm not familiar with the `%frameWrapper` syntax enough to know exactly when the wrapper will be disposed. So I wanted to double check.

**Comment by amaitland** [comment]
I also changed the callbacks so after you execute they set the underlying `MCefRefPtr` instance to `NULL`. If you've got a cleaner way then I'm all for it :+1:

**Pull request merged**
