### PR TITLE
CefFrameWrapper implementation

### PR DESCRIPTION
**Pull request by rassilon**
Start stubbing out some implementations in CefFrameWrapper.h

(This doesn't build yet, don't bother trying... )

This is the PR related to #987.

### CODE REVIEW

**Comment by amaitland** [comment]
I was thinking this one a little bit the other day, ideally we'd

- Create an `IFrame` interface, similar to `IRequest`
- Replace `isMainFrame` bool param with `IFrame` reference

**Comment by amaitland** [comment]
As `41` is turning into a bit of an overhaul, I'd even consider removing the `Cut/Copy/Paste` methods from the `ChromiumWebBrowser` instances.

**Comment by rassilon** [comment]
An `IFrame` interface would make sense. I'm not sure what you mean by `isMainFrame` bit though.

While I was doing my silly copying and pasting I was looking at `MCefRefPtr` and wondering: When should I be using this vs just using `CefRefPtr<>`. Sadly, the file lacks any useful comments.

**Comment by amaitland** [comment]
> I'm not sure what you mean by isMainFrame bit though.

`IRequestHandler.OnBeforeBrowse` as an example, replace the `isMainFrame` bool with the `IFrame` interface.

> While I was doing my silly copying and pasting I was looking at MCefRefPtr and wondering: When should I be using this vs just using CefRefPtr<>. Sadly, the file lacks any useful comments.

I was under the impression you use `MCefRefPtr` in `ref class's`

**Comment by amaitland** [comment]
`MCefRefPtr` is one of those `black magic` things that's always been there, so I can't provide any definitive information.

**Comment by rassilon** [comment]
`MCefRefPtr` seems to be to help with C++/CLI compilation weirdness.

CefFrame has a GetBrowser() method. However, CefSharp uses `IWebBrowser` that conflates the top level browser window and the browser control host.

So, should GetBrowser return an `IBrowserWindow` interface that wraps JUST `CefBrowser`?

Bill

**Comment by rassilon** [comment]
Oh, ick. I just realized, ClientAdapter.cpp's FocusHandler methods doesn't verify it's the main frame for the browser control. (and I'm sure similarily with the rest of them) Blech.

Bill

**Comment by amaitland** [comment]
> MCefRefPtr seems to be to help with C++/CLI compilation weirdness.

Yep, you need it to host the `unmanaged` classes.

> CefFrame has a GetBrowser() method. However, CefSharp uses IWebBrowser that conflates the top level browser window and the browser control host.

I would have left `GetBrowser()` out from the implementation. Confuses things otherwise and I don't think it's strictly necessary, having a reference to `IWebBrowser` allows you to do the basics, load/stop/back/forward etc. Thoughts?

**Comment by amaitland** [comment]
> Oh, ick. I just realized, ClientAdapter.cpp's FocusHandler methods doesn't verify it's the main frame for the browser control. (and I'm sure similarily with the rest of them) Blech.

Do the focus methods pass in a reference to `CefFrame`?

**Comment by amaitland** [comment]
What do you think about removing `Cut/Copy/Paste/etc` from `IWebBrowser` and using the new Frame wrapper instead? Since `41` is turning into and overhaul.

**Comment by rassilon** [comment]
> I would have left GetBrowser() out from the implementation. Confuses things otherwise and I don't think it's strictly necessary, having a reference to IWebBrowser allows you to do the basics, load/stop/back/forward etc. Thoughts?

I'm leaving it out for now, but it does make life complicated if we want to factor things out more like CEF. (i.e. allow CefBrowser ids to be publicly accessible for instance)

> Do the focus methods pass in a reference to CefFrame?

No, just CefBrowser.

> What do you think about removing Cut/Copy/Paste/etc from IWebBrowser and using the new Frame wrapper instead? Since 41 is turning into and overhaul.

We could do that later, sure. There're pretty harmless overloads for now.
We could mark them as Deprecated I think in 41 if we wanted as well.

**Comment by rassilon** [comment]
Due to `IFrame` needing to invoke the `BrowserServiceHost` is why the whole `IBrowserAdapter` goo got added. Thoughts?

Bill

**Comment by rassilon** [comment]
> I'm leaving it out for now, but it does make life complicated if we want to factor things out more like CEF. (i.e. allow CefBrowser ids to be publicly accessible for instance)

Without a CefBrowserWrapper we also pass in the wrong context for things like `OnBeforePopup` since the CefBrowser might not be the main CefBrowser.

**Comment by amaitland** [comment]
I'd somewhat forgotten supporting popups, we don't handle that scenario well at all. In light of that we should wrap CefBrowser.

**Comment by rassilon** [comment]
> I'd somewhat forgotten supporting popups, we don't handle that scenario well at all. In light of that we should wrap CefBrowser.

Should we rename CefBrowserWrapper to be CefSubBrowserAdapter and then write CefBrowserWrapper for IBrowser?

**Comment by rassilon** [comment]
Or if not IBrowser, then something that helps distinguish between the concepts of IWebBrowser and the CefBrowserWrapper interface name.

**Comment by rassilon** [comment]
@amaitland , Think I should push this set of changes into 2272 for testing? I did a bunch of work of moving this stuff forward by creating `IBrowser` as the interface wrapper of CefBrowser.

**Comment by amaitland** [comment]
Go for it :+1:

**Pull request merged**
