### PR TITLE
Fix enums, integer and doubles binding behavior

### PR DESCRIPTION
**Pull request by joaompneves**
Bind behavior of the default binder was broken for enums. 
Eg: trying to convert an integer to an enum always resulted in the enum default value (0).

Convertion from doubles to ints or ints to doubles was also broken. Now it tries to convert with precision loss if applicable.

JS -> .Net
1 -> B (enum { A, B } )
2.4 -> 2 (int)
2.6 -> 3 (int)
2 -> 2 (double)

### CODE REVIEW

**Comment by perlun** [comment]
Looks good to me. @amaitland, I think you're the one who's done most of the work on this file so I wouldn't mind you reviewing it also before we merge.

**Comment by amaitland** [comment]
@perlun I haven't had a chance to see the unit tests run, so was waiting to merge. I had added it to the `63` milestone as I do have plans to merge it.

**Comment by perlun** [comment]
> @perlun I haven't had a chance to see the unit tests run, so was waiting to merge. I had added it to the 63 milestone as I do have plans to merge it.

Ah, sorry to rush you! 😄 Thanks for the merge.

Regarding the test runs - would it make sense if we added the test output to AppVeyor, so we could more easily see results of tests (without having to download the branch and test it locally)?

**Comment by amaitland** [comment]
@perlun Excellent suggestion, feel like creating an issue to represent the idea?

**Comment by perlun** [comment]
Done - see #2227.

**Pull request merged**
