### PR TITLE
check if the visual is connected

### PR DESCRIPTION
**Pull request by marinkobabic**
if the visual is not connected the whole application will crash

### CODE REVIEW

**Comment by amaitland** [comment]
Please provide a code sample that reproduces the problem. 

You can either include in the PR or fork https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by marinkobabic** [comment]
I tried to reproduce the issue several times without success. I can provide
you a sracktrace if it helps? Actually I have no idea how to get it
reproduced.

**Comment by marinkobabic** [comment]
Anwendung: MyApp.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.InvalidOperationException
   bei System.Windows.Media.Visual.PointToScreen(System.Windows.Point)
   bei CefSharp.Wpf.ChromiumWebBrowser.UpdateBrowserScreenLocation()
   bei System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   bei System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   bei System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   bei System.Windows.Application.RunDispatcher(System.Object)
   bei System.Windows.Application.RunInternal(System.Windows.Window)
   bei MyTraderBot.App.Main()

**Comment by amaitland** [comment]
Yes please add the stack trace. 

Related to issue #2106

**Comment by chris-araman** [comment]
@amaitland, would it be possible to pick this up for a 63.0.3 release? Our crash counts have increased significantly due to this bug.

Are you still accepting bounties here?
https://www.bountysource.com/issues/53873953-funding-request-release-63-0-0

**Comment by amaitland** [comment]
> @amaitland, would it be possible to pick this up for a 63.0.3 release? Our crash counts have increased significantly due to this bug.

Yep, I can do that.

> Are you still accepting bounties here?
> https://www.bountysource.com/issues/53873953-funding-request-release-63-0-0

Yep, that's fine 👍

**Comment by amaitland** [comment]
merged into `cefsharp/63` with commit https://github.com/cefsharp/CefSharp/commit/58e705244bef8ce56e6e2f6578ab648d792c4b04

**Comment by chris-araman** [comment]
@amaitland, you should see a contribution from @lsurazski regarding this fix. I saw the new release tag. How are the new NuGet packages coming along? Do you think you'll find time to release these today?

**Comment by amaitland** [comment]
> @amaitland, you should see a contribution from @lsurazski regarding this fix.

@chris-araman Thank you!

> Do you think you'll find time to release these today?

They've been pushed to `Nuget.org`, will appear shortly (usually within the hour). Let me know if there's any problem.

**Pull request merged**
