### PR TITLE
WPF - Modify CopyMemory EntryPoint to work with .Net Core

### PR DESCRIPTION
**Pull request by kpreisser**
Contributes to #2796

**Summary:**
   - Fixed the `CopyMemory` entrypoint declaration, which is not working on .NET Core 3.0 as `kernel32.dll` doesn't have an `CopyMemory` export.

**Changes:**
- Changed `EntryPoint` from `CopyMemory` to `RtlCopyMemory`
- Changed the `numberOfBytes` parameter from `uint` to `UIntPtr`

Note: I believe using an pointer type (`IntPtr` or `UIntPtr`) for the `numberOfBytes` parameter is correct even though pinvoke.net (and other sites) specify it as `int`, because the documentation for [`CopyMemory`/`RtlCopyMemory`](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366535%28v%3dvs.85%29) declares it as `SIZE_T` which is defined as pointer-sized integer (`ULONG_PTR`). Additionally, I have done some testing to verify that the value is actually interpreted as 64-bit integer when running as x64 (by specifying a value greater than 0xFFFFFFFF and verifying the correct number of bytes was copied).

Note: There is also a managed API [`Buffer.MemoryCopy()`](https://docs.microsoft.com/en-us/dotnet/api/system.buffer.memorycopy?view=netcore-3.0#System_Buffer_MemoryCopy_System_Void__System_Void__System_Int64_System_Int64_) that could be used instead of p/invoking `RtlCopyMemory`/`RtlMoveMemory`, available starting with .NET Framework 4.6, but that one seems to be slower.
      
## How Has This Been Tested?

Tested manually using `CefSharp.MinimalExample.NetCore.Wpf` (see https://github.com/cefsharp/CefSharp.MinimalExample/pull/57)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated documentation

**Checklist:**
- [X] Tested the code(if applicable)
- [X] Commented my code
- [ ] Changed the documentation(if applicable)
- [ ] New files have a license disclaimer
- [X] The formatting is consistent with the project (project supports .editorconfig)

### CODE REVIEW

**Comment by amaitland** [comment]
> * Changed `EntryPoint` from `CopyMemory` to `RtlMoveMemory`

Is there a reason you chose `RtlMoveMemory` over `RtlCopyMemory`? I see no reason to use the slower move memory.

> Note: There is also a managed API [`Buffer.MemoryCopy()`](https://docs.microsoft.com/en-us/dotnet/api/system.buffer.memorycopy?view=netcore-3.0#System_Buffer_MemoryCopy_System_Void__System_Void__System_Int64_System_Int64_) that could be used instead of p/invoking `RtlMoveMemory`, available starting with .NET Framework 4.6, but that one seems to be slower.

As we only target `.Net 4.5.2` this isn't an option anyway.

**Comment by kpreisser** [comment]
> Is there a reason you chose `RtlMoveMemory` over `RtlCopyMemory`? I see no reason to use the slower move memory.

No particular reason, I was just following the comments in https://github.com/dotnet/coreclr/issues/24008 for changing `CopyMemory` to `RtlMoveMemory` (I assume because it doesn't require buffers to not overlap and so is safer).

I updated the PR to use the faster `RtlCopyMemory` instead.
Thanks!

**Comment by amaitland** [comment]
> (I assume because it doesn't require buffers to not overlap and so is safer).

Actually it would appear to be that `RtlCopyMemory` only exists for `x64` as detailed in https://stackoverflow.com/a/47016390/4583726

Confirmed in the output of `dumpbin /exports kernel32.dll` there is indeed no `RtlCopyMemory`.

> #define RtlCopyMemory(Destination,Source,Length) memcpy((Destination),(Source),(Length))

`winnt.h` calls `memcpy`, so changing to directly call [memcpy](https://www.pinvoke.net/default.aspx/msvcrt/memcpy.html) appears to be one option.

The other being to use [NativeMethodWrapper.CopyMemoryUsingHandle](https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Core/NativeMethodWrapper.cpp#L13) which I had previous added with the intention of bench marking to see if the native call was quicker than the `p/invoke` call. (Crappy method name I know, from memory it I couldn't call it `CopyMemory` or `RtlCopyMemory` as the macros interfere with the method name).

**Comment by amaitland** [comment]
Changed to use native wrapper around `RtlCopyMemory` in https://github.com/cefsharp/CefSharp/commit/b1b930605c0b9d2a74da54506bfdef4263d11a65

Originally the `Rendering` implementation in `WPF` was written in `VC++` and used [MemoryCopy](https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp.Core/Internals/RenderClientAdapter.h#L182) so I'm comfortable it's well tested.

**Comment by kpreisser** [comment]
Thank for your the background information and the fix! Sorry, I didn't test running as x86 after changing the PR from `RtlMoveMemory` to `RtlCopyMemory`, so I didn't notice it was missing on x86.

(As additional thought, since kernel32's `RtlMoveMemory` gets forwarded to ` NTDLL.RtlMoveMemory`, it might be more reliable to use that one as it is [documented](https://docs.microsoft.com/en-us/windows/win32/devnotes/rtlmovememory), whereas `kernel32.RtlMoveMemory` has only [archived documentation](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366788%28v%3dvs.85%29). But no need to change that of course since using `memcpy` from the CRT should be fine and is slightly faster.)

Thanks!

**Comment by amaitland** [comment]
> Sorry, I didn't test running as x86 after changing

All good 😄 Makes no sense that it exists on `x64` and not `x86`.

**Pull request merged**
