### PR TITLE
Upgraded CEF to version 60

### PR DESCRIPTION
**Pull request by GrabzIt**

### CODE REVIEW

**Comment by BhanuprakashReddy** [comment]
When will we wait for CEF build version 62 with mp3 support for audio playing. Please let us know the expected date of developer version of CEFSharp-62. We are eagerly waiting for roll out . . .

**Comment by GrabzIt** [comment]
As mentioned elsewhere a release is being blocked by #1203 if you want to submit a fix please fell free.

**Comment by perlun** [comment]
@amaitland @jornh What do you think about merging this one? Or do you think it's better to go straight on 62 or 63?

**Comment by amaitland** [comment]
@perlun I have no objection to merging this, ideally fix the minor formatting and cleanup the code duplication. Neither of which are show stoppers. Go with whatever works for you 😄 I have no requirement for a newer version at this point in time.

**Comment by perlun** [comment]
@GrabzIt If you don't mind, I intend to merge this (by squashing the commits onto master.) Let me know if you want it done some other way, or merge it yourself if you like. 😉

**Comment by GrabzIt** [comment]
@perlun no I don't mind, please go ahead.

**Pull request merged**
