### PR TITLE
Rename NavStateChanged to LoadingStateChanged

### PR DESCRIPTION
**Pull request by amaitland**
Remove the old `IWebBrowserInternal.SetIsLoading` method and cleanup code.

Also remove the lock as now the methods simply fire off events.

### CODE REVIEW

**Comment by rassilon** [comment]
This looks good to me.

**Comment by amaitland** [comment]
@rassilon On a slightly different note were you still interested in implementing a `async` version of `ResourceHandler`?

**Comment by rassilon** [comment]
Yeah, but I've been knee deep in Windows Imaging for a bit at work.  I've got it (Win8.1 Embedded) happy in my VM of choice, now I need to try it out with my Surface Pro 3.

I did manage to upgrade my work project to 39.0.0 which was very nice.

Bill

**Comment by amaitland** [comment]
> Yeah, but I've been knee deep in Windows Imaging for a bit at work.

I've built some `Windows Standard 7 Embedded`, surprisingly a very time consuming task!

**Pull request merged**
