### PR TITLE
Create JS objects from dictionaries

### PR DESCRIPTION
**Pull request by darvell**
This allows any JS binding to return a dictionary of Dictionary< String, Object > and converts that into a standard javascript object.

Not sure if this is the cleanest way to do it, this is my first foray in to .NET C++!

### CODE REVIEW

**Comment by amaitland** [comment]
@darvell Thanks for the contribution! This is somewhat an interesting one, there is already PR #893 which adds `Dictionary` support in a very different fashion.

I'm unsure which approach is better long term, so probably needs to be discussed.

What was your usage scenario? In general it would be handy to include an example to demo your project. e.g. add to `CefSharp.Example.BoundObject`

**Comment by darvell** [comment]
My usage case would be passing a Javascript object to C#, modifying it then sending it back. 

It seems most usages would suggest to just send the object to C#, modify it, then send it back as a serialized string and run JSON.parse() on the result but that seems awfully unnecessary to do deserialize-modify-serialize-deserialize.

I'll see about creating an example in CefSharp.Example.BoundObject in the next day since I don't think it's very clear without it!

**Comment by amaitland** [comment]
There are quite a few limitations with this though, like only supporting primitive types for the value in the dictionary. Complex objects won't pass through the `WCF` proxy, hence the need to `JSON` serialize yourself in some scenarios.

If #893 were to be merged then this code would most likely be redundant. Hence the need for discussion.

**Comment by rassilon** [comment]
Hrm. I think I agree with @amaitland  that #893 is more promising. Not to mention serialization issues are detected much more quickly for #893 (in the browser process instead of in the render sub process)

**Comment by amaitland** [comment]
@darvell Did you have a chance to checkout #893? Any comments?

**Comment by darvell** [comment]
Looks like a better approach in the end. While I still think that being able to properly send JS objects around would be really beneficial, my approach is further looking like the wrong way to handle that use-case.

**Pull request closed without merging**
