### PR TITLE
Enhancement - Pluggable Javascript Naming

### PR DESCRIPTION
**Pull request by amaitland**
**Fixes:** #2442

**Summary:** 
Follow up to https://github.com/cefsharp/CefSharp/commit/898ca38e7a7261b3a42c33b2abf5eac6c022ddde

- Moves NameConverter to IJavascriptObjectRepository
- Removes `BindingOptions.CamelCaseJavascriptNames `

**Changes:** 
- Javascript Binding implementation now has a pluggable naming implementation
- Naming Converter is also used for javascript callbacks
- The new `CamelCaseJavascriptNameConverter` will convert returned property names
- `LegacyCamelCaseJavascriptNameConverter` is the default and will preserve the existing behaviour for upgrading users
- Doesn't effect naming for returned objects when using the older **sync** binding
      
**How Has This Been Tested?**  
- Javascript Binding Test passes
- Includes some new unit tests (more required)

**Types of changes**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated documentation

**Checklist:**

- [x] Tested the code(if applicable)
- [x] Commented my code
- [x] Changed the documentation(if applicable)
- [x] New files have a license disclaimer
- [x] The formatting is consistent with the project (project supports .editorconfig)

### CODE REVIEW

**Comment by amaitland** [comment]
TODO:
- [ ] `DefaultBinder` needs to be upgraded to support `IJavascriptNamingConverter`
- [ ] Add Unit Tests (Possibly some in https://github.com/cefsharp/CefSharp/pull/2231/files#diff-d5a2c335de34e13e7d04a3681643f9cc that can be adapted)
- [ ] Investigate TODO in code comment.

**Comment by amaitland** [comment]
For those wishing to disable camel casing of names the `BindingOptions.CamelCaseJavascriptNames ` property has been removed, you now simply set `JavascriptObjectRepository.NameConverter = null`

```c#
//Before
objectRepository.Register("myObject", new MyObject(), new BindingOptions { CamelCaseJavascriptNames = false });

//After
objectRepository.NameConverter = null;
objectRepository.Register("myObject", new MyObject(), new BindingOptions { });
```

**Comment by veronikavychodilova** [comment]
> 
> 
> For those wishing to disable camel casing of names the `BindingOptions.CamelCaseJavascriptNames ` property has been removed, you now simply set `JavascriptObjectRepository.NameConverter = null`
> 
> ```cs
> //Before
> objectRepository.Register("myObject", new MyObject(), new BindingOptions { CamelCaseJavascriptNames = false });
> 
> //After
> objectRepository.NameConverter = null;
> objectRepository.Register("myObject", new MyObject(), new BindingOptions { });
> ```

Hi, I've tried to upgrade  cefSharp.Winforms from v84.4.10 to latest stable (v86.0.241) and after that the binding stopped working - I was getting following error: TypeError: Cannot read property 'EditorInit' of undefined.

I've only changed the original code:
`WebBrowser.JavascriptObjectRepository.Register("editorInit", _editorInit, true, new BindingOptions { CamelCaseJavascriptNames = false });
            WebBrowser.JavascriptObjectRepository.Register("codeChange", _codeChange, true, new BindingOptions { CamelCaseJavascriptNames = false });
            WebBrowser.JavascriptObjectRepository.Register("editorOpen", _editorOpen, true, new BindingOptions { CamelCaseJavascriptNames = false });`

to new code (as stated in your suggestion):
`WebBrowser.JavascriptObjectRepository.NameConverter = null;
            WebBrowser.JavascriptObjectRepository.Register("editorInit", _editorInit, true, new BindingOptions { });
            WebBrowser.JavascriptObjectRepository.Register("codeChange", _codeChange, true, new BindingOptions { });
            WebBrowser.JavascriptObjectRepository.Register("editorOpen", _editorOpen, true, new BindingOptions { });`

Am I missing something there? Thank you.

**Comment by amaitland** [comment]
Please use the https://github.com/cefsharp/CefSharp/discussions section to ask questions. Thanks.

**Pull request merged**
