### PR TITLE
Update CefExample.cs

### PR DESCRIPTION
**Pull request by Jayman1305**
Implemented dynamic detection of the proxy using IE settings.

### CODE REVIEW

**Comment by Jayman1305** [comment]
I have tried twice now. Even the documentation doesnt help https://help.github.com/articles/merging-a-pull-request/. I do not see a Merge Pull Request option anywhere.

**Comment by Jayman1305** [comment]
It says 
This branch has pending checks, but can be merged.
Only those with write access to this repository can merge pull requests. so if possible, @amaitland  please can you merge the 2.

**Comment by amaitland** [comment]
Locally, merge https://github.com/Jayman1305/CefSharp/tree/patch-6 into https://github.com/Jayman1305/CefSharp/tree/patch-4

Then push the changes to github, they'll show up in PR #896

**Comment by amaitland** [comment]
Both need to be tested together before merging.

**Comment by Jayman1305** [comment]
Thanks @amaitland I deleted them both for now as i cant install the local github client in office. Will resume from home.

**Pull request closed without merging**
