### PR TITLE
Add Ability to Disable WCF

### PR DESCRIPTION
**Pull request by arsher**
added switch to turn off wcf (this disables js bindings and eval script)

### CODE REVIEW

**Comment by amaitland** [comment]
Thanks @arsher I'll look at merging this in shortly.

**Comment by rassilon** [comment]
Looks good to me.

**Comment by amaitland** [comment]
I made a few additional commits to `master`, most important being https://github.com/cefsharp/CefSharp/commit/ff695dbf6d3f9c24f1db041c3cce9dde23822fe7

**Comment by amaitland** [comment]
I had also considered moving the `WcfEnabled` flag onto the `Cef` object, so it could be changed at runtime (under certain circumstances). Thoughts?
(There are some technical limitations to this as the `VC++` compiler complains, so we'll likely have to create a new object to store the bool).

**Pull request merged**
