### PR TITLE
Resolve build issues for projects without app.config

### PR DESCRIPTION
**Pull request by deonberlin**
**Fixes:** #3390

**Summary:**
   - Added condition to build target to check if app.config exists

**Changes:** [specify the structures changed] 
   - Build target condition for @(AppConfigWithTargetPath) added
      
**How Has This Been Tested?**  

  - build package
  - referenced newly crated package in a library project without app.config
  - build library project successfully

**Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated documentation

**Checklist:**

- [ ] Tested the code(if applicable)
- [ ] Commented my code
- [ ] Changed the documentation(if applicable)
- [ ] New files have a license disclaimer
- [x] The formatting is consistent with the project (project supports .editorconfig)

### CODE REVIEW

**Comment by amaitland** [comment]
Thanks 👍 This is only part of it, we need to add the equals empty check to the CefSharpPlatformCheck target as well.

Users with a PlatformTarget of AnyCPU and without an app.config need to be informed extra steps are required to make AnyCPU work.

**Comment by amaitland** [comment]
Testing this change and it fails with 

```
error MSB4099: A reference to an item list at position 120 is not allowed in this condition "Exists('$(CefSharpTransformXmlDllPath)') AND '$(PlatformTarget)' == 'AnyCPU' AND '$(CefSharpAnyCpuSupport)' == '' AND '@(AppConfigWithTargetPath)' != ''". [C:\projects\CefSharp.MinimalExample\CefSharp.MinimalExample.WinForms\CefSharp.MinimalExample.WinForms.net472.csproj
```

**Comment by deonberlin** [comment]
Interesting. How did you test that, because the condition in the error message doesn't match my code changes, it matches my comment.

I've tested by simply modifying the buildTransitive\CefSharp.Common.targets file in the nuget package cache, and for me it works.

The reference to the list condition can of course only evaluated after the target _CopyAppConfigFile has run.

**Comment by amaitland** [comment]
I applied the changes manually then generated a new set of Nuget packages, it's when I perform a Nuget upgrade it fails. I've also tried your exact commit (Please target PRs again master in future)

> I've tested by simply modifying the buildTransitive\CefSharp.Common.targets file in the nuget package cache, and for me it works.

Did you close and reopen your solution to make sure visual studio reflected the changes? Targets files are cached. 

> The reference to the list condition can of course only evaluated after the target _CopyAppConfigFile has run.

The condition should still evaluate without exception regardless of when it's run as it's a simple equals and not equals.

**Comment by deonberlin** [comment]
> Please target PRs again master in future

I had the hope for an update on the 87 package, that's why I targeted this branch.

> Did you close and reopen your solution to make sure visual studio reflected the changes? Targets files are cached.

Yes I did, and actually each change in the target file was applied in the next build, at least here on my machine.

> The condition should still evaluate without exception regardless of when it's run as it's a simple equals and not equals.

I had thought so too. Actually I've copied that condition from the definition of _CopyAppConfigFile, but the error messages states it's invalid, even if the same condition must have been evaluated correctly, because _CopyAppConfigFile was executed before.

I'll try to reproduce the error.

**Comment by amaitland** [comment]
I've squashed your changes and merged into master in commit https://github.com/cefsharp/CefSharp/commit/d36c0bceb3335d76b355ef7cf3c74dafe4a80805

Build 88.2.10-CI3900 should be available from https://www.myget.org/gallery/cefsharp for testing purposes. I'll run another Nuget upgrade tomorrow,  make sure I didn't make a mistake somewhere. Your welcome to test out the packages.

**Comment by deonberlin** [comment]
The packages 88.2.10-CI3900 are working fine on my side with all platforms and for AnyCPU with and without CefSharpAnyCpuSupport.

**Comment by amaitland** [comment]
This has been merged into the `cefsharp/88` branch and is included in the `88.2.40-pre` release, see https://github.com/cefsharp/CefSharp/issues/3389#issuecomment-776506045 for details.

**Pull request closed without merging**
