### PR TITLE
疑问

### PR DESCRIPTION
**Pull request by wangzheng888520**
如果我希望用XP系统，该如何操作

### CODE REVIEW

**Comment by amaitland** [comment]
Can you translate in English?

**Comment by jgglg** [comment]
he wants to use cefsharp in the xp OS, so how to do for that.

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#XPSupport

**Comment by amaitland** [comment]
If you require assistance then please create an issue. A `Pull Request` is not the appropriate place.

**Comment by wangzheng888520** [comment]
thanks amaitland and jgglg , I am a Chinese,and my English is too bad, but i very want to study with all of the developers on github.   thanks for your help.

**Pull request closed without merging**
