### PR TITLE
Updated OnTooltipChanged to allow for modifying text

### LINKED ISSUE #1648: Feature Request - Update OnTooltipChanged to allow for modifying text
Update `IDisplayHandler.OnTooltipChanged` so that `text` can be modified (make `ref` param)

### PR DESCRIPTION
**Pull request by merceyz**
Resolves #1648

- Made it possible to modify the `text` parameter

- Updated the examples accordingly

- Added a DisplayHandler to the WPF example

### CODE REVIEW

**Comment by amaitland** [comment]
> When window rendering is disabled the application is responsible for drawing tooltips and the return value is ignored. 

http://magpcss.org/ceforum/apidocs3/projects/(default)/CefDisplayHandler.html#OnTooltip(CefRefPtr%3CCefBrowser%3E,CefString&)

The documentation implies it should be called for normal rendering, will need to be looked into further.

**Comment by merceyz** [comment]
Not according to the issue I linked to in the source, one could of course ask Marshall

**Comment by amaitland** [comment]
That issue hasn't been updated in years. I'd first look through the CEF source before asking.

**Comment by merceyz** [comment]
Issue recently updated, see https://bitbucket.org/chromiumembedded/cef/issues/783/add-cefdisplayhandlerontooltip-call-for#comment-36392203

**Comment by amaitland** [comment]
Guess that clarifies things. If you see value in this for the `WPF` version then by all means merge away. Should probably update #1648 as well.

**Pull request merged**
