### PR TITLE
FolderSchemeHandlerFactory - change resource file share mode.

### PR DESCRIPTION
**Pull request by igor-eremyashev**
This small change will allow hot edit and reload for local pages, which is helpful for development purposes.

### CODE REVIEW

**Comment by amaitland** [comment]
I'm not sure `ReadWrite` should be the default, happy for it to be configurable. It should probably be readonly when you deploy an app into production (unless you really know what your doing, in which case the `FolderSchemeHandlerFactory` probably isn't suitable).

**Comment by igor-eremyashev** [comment]
It is always possible to close an application, modify its pages and then start it again. The only difference is `FileShare.Read` won't allow to do that without restart. The only way to prevent page resources from modification I can think of is to store them as embedded resources and sign the assembly.

**Comment by amaitland** [comment]
> It is always possible to close an application, modify its pages and then start it again. The only difference is `FileShare.Read` won't allow to do that without restart.

It's modification whilst attempting a `Read` that I'd be concerned about.

**Comment by igor-eremyashev** [comment]
Would you prefer to have `FileShare` constuctor parameter or a boolean flag to configure this behavior?

**Comment by amaitland** [comment]
Using the FileShare enum makes it clearer I think.

**Pull request merged**
