### PR TITLE
Refactor CefSharp.Core into CefSharp.Core.Runtime

### PR DESCRIPTION
**Pull request by amaitland**
**Summary:** 

Restructure projects/packages to
- Better support `.Net Core/5.0`
- `CefSharp.Core.dll` is now written in `C#` with `CefSharp.Core.Runtime.dll` being the runtime dependency that provides the `Mixed Mode CLI/C++` implementation. 
- Simplify `AnyCPU` targeting 
- Resolves issue with `pacakges.config` based projects having to reload the solution for the dependencies to show up
- Remove requirement for package consumers having to change `$(Platform)` at the solution level ($PlatformTarget) at project level is now sufficient
- Greater control over how `libcef.dll` is loaded.
- Potential to add additional runtime checks like validating `VC++` is installed.
- Upgrade `GitLink`

**Changes:**

- Convert from `x86/x64` to `AnyCPU`.
  - `CefSharp.dll`
  - `CefSharp.WinForms.dll`
  - `CefSharp.Wpf.dll`
  - `CefSharp.OffScreen.dll`
  - Included in `lib\net452` folder in `Nuget` packages, can no longer be moved by setting `CefSharpTargetDir` property in `project file (msbuild)`. 
  
- Rename `CefSharp.Core.dll` to `CefSharp.Core.Runtime.dll`
  - No longer directly referenced by client applications
  - All the `Public API` methods it exposes are hidden from `Visual Studio Intellisense`
  - Used indirectly through new `CefSharp.Core.dll` (`AnyCPU` class library).
    
- Add `CefSharp.Core.dll`
  - Managed (`AnyCPU`) dll that provides the public `API`
  - In `.Net Core` there will be a `CLR Module Initializer` to load `libcef.dll` from the relevant location where required
  - Additional runtime checks can be added to validate if say `VC++` is installed
  - Generally give more control over loading of the unmanaged resources and setting the relevant paths e.g. BrowserSubProcessPath
  - NOTE: In Theory we could use a `CLR Module Initializer` in `.Net 4.5.2` and load the dlls at runtime to support `AnyCPU`,
    this would require some breaking changes to the public API, so have added support for a `app.config` transform based on #3168
      
**How Has This Been Tested?**  
Unit tests pass sucessfully. The `MinimaExample` works in the cases tested so far.

**Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Updated documentation

**Checklist:**

- [x] Tested the code(if applicable)
- [x] Commented my code
- [x] Changed the documentation(if applicable)
- [x] New files have a license disclaimer
- [x] The formatting is consistent with the project (project supports .editorconfig)

### CODE REVIEW

**Comment by amaitland** [comment]
TODO:
- [ ] Determine if we can use [Arch Specific](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders) folders to get around having to implement the hack added in commit https://github.com/cefsharp/CefSharp/pull/3311/commits/5d4cd243c6d9687d63f1c6b0b6bc256561267d29
  It's likely to be a little bit hacky using the `.Net 452` dlls in a `netcoreapp3` folder
- [ ] Fix typos in new `Cef` class ( #3306)

**Comment by amaitland** [comment]
I'm going to merge this now, there's still likely a few issues to resolve. Once `AppVeyor` creates a new set of packages that'll be easier to test with so will resolve them after merge.

**Comment by amaitland** [comment]
The `Ref` Assemblies don't appear to be build correctly on `AppVeyor`.

https://ci.appveyor.com/project/cefsharp/cefsharp/builds/36859715/job/lmn6djbvfijk3fui#L591

**Comment by Nickman87** [comment]
@amaitland Awesome seeing this work towards the new .Net 5! Are these changes already available somehow trough NuGet to try out?

**Comment by amaitland** [comment]
@Nickman87 Yes, packages are available on https://www.myget.org/gallery/cefsharp

Issue https://github.com/cefsharp/CefSharp/issues/3197 has the Net Core/5  specific details,  if you can report your findings there that would be greatly appreciated.

**Pull request merged**
