### PR TITLE
Enhancement Wpf High DPI

### PR DESCRIPTION
**Pull request by amaitland**
Based on #858 targeted against `2272`

### CODE REVIEW

**Comment by bjarteskogoy** [comment]
What is the state of this pull request in regard to the latest development of cefsharp?

**Comment by amaitland** [comment]
> What is the state of this pull request in regard to the latest development of cefsharp?

Development is now happening on `master`, so this would need to be re-targeted, updated and thoroughly tested. This isn't a priority for me personally as I have no need for `HiDpi` support.

Have you been using it in production?

**Comment by bjarteskogoy** [comment]
We've been using this in production for some months. We haven't experienced any particular issues.
Do you believe a rebase woulb be possible or is the master branch changed so much that it would be better to rewrite it?

**Comment by amaitland** [comment]
A lot has changed, so it's hard to say.

**Comment by amaitland** [comment]
Some `upstream` improvements have been made in the context of `HiDPI`

https://bitbucket.org/chromiumembedded/cef/commits/260526953e056cb27edbb569166da63c6cb4d5c0
https://bitbucket.org/chromiumembedded/cef/commits/c27da0e7b120704fe2480aec7bfb624fe52ebda3

Hopefully with a little digging we can port those over to the `WPF` project without too much effort. (Possibly need to get the latest `2357` build which will hopefully be available on `cefbuilds.com` in the next week).

**Comment by amaitland** [comment]
Closing this in favor of #1207

**Pull request closed without merging**
