### PR TITLE
Rewrite ResourceHandler/SchemeHandler

### PR DESCRIPTION
**Pull request by amaitland**
Rebased version of #950 on `2272`

### CODE REVIEW

**Comment by amaitland** [comment]
@rassilon Thanks for the merge :+1:

**Comment by amaitland** [comment]
Make sure to test that problems discovered with https://github.com/cefsharp/CefSharp/commit/a0460e83d81bb7964d9027af2f69f277507443d1 have been resolved.

**Comment by rassilon** [comment]
The changes in a0460e8 seem odd. What was the underlying cause of the problem?

**Comment by rassilon** [comment]
Oh, could it be due to `CefExmaple.RegisterTestResources` being an async method but it doesn't:

* Return a Task type like it should.
* Utilize `.ConfigureAwait(continueOnCapturedContext: false)`

Thus, the `SyncronizationContext` is the UI thread for `BrowserTabUserControl` (in the WinForms example).

I'm not sure how this relates exactly to a0460e8 though. I would have thought `ProcessRequestAsync` would run on a non-UI thread so that `Task.Run` would run against the correct `SyncronizationContext/TaskScheduler`.

Bill

**Comment by amaitland** [comment]
> The changes in a0460e8 seem odd. What was the underlying cause of the problem?

Unsure, just know it was throwing a `ContextSwitchDeadlock`.

Seems to be sorted now, so I've switched to using a task again, aka https://github.com/amaitland/CefSharp/commit/48268721c054f84c4da59b2f090c1030372a58f9

**Comment by rassilon** [comment]
Problems that disappear are always nice. :smile:

**Comment by amaitland** [comment]
> Problems that disappear are always nice. :smile:

Indeed :smile:

**Comment by rassilon** [comment]
Merged up from 2272 head again.

**Comment by amaitland** [comment]
Merging this now, will look at finished the `async` implementation of resource handler in the not too distant future.

**Pull request merged**
