### PR TITLE
fix: VisitUrlCookiesAsync NullReferenceException #1928

### PR DESCRIPTION
**Pull request by bobahml**
The error contained in TaskCookieVisitor class. 
Method Dispose set taskCompletionSource=null, and then property Task called by an external code.

### CODE REVIEW

**Comment by amaitland** [comment]
Great you've attempted a fix 👍 Please update the description with details of what your proposed changes achieve. 

Have you attempted to implement it in your code and verified it works? Obviously you can implement your own handler that has your proposed changes

I'm concerned you'll end up with a Task that's never executed.

**Comment by amaitland** [comment]
> I'm concerned you'll end up with a Task that's never executed.

Ignore that, it should be ok. 

Review your changes above, formatting is out. Spaces not tabs thank you!

**Comment by amaitland** [comment]
Thinking about it a little more, I think we should `return null` and update the documentation.

> Returns false if cookies cannot be accessed. 

`VisitUrlCookies` returning `false` means something different to there not being any cookies.

https://github.com/cefsharp/CefSharp/blob/cefsharp/55/CefSharp.Core/CookieManager.cpp#L104

**Comment by bobahml** [comment]
I think it would be correct to throw an exception immediately if the method is called from no suitable thread.

**Comment by amaitland** [comment]
> I think it would be correct to throw an exception immediately if the method is called from no suitable thread.

I'm fine with that, it's not clear if they explicitly need to be called on the `CEF IO` thread or not.

See http://magpcss.org/ceforum/apidocs3/projects/(default)/CefCookieManager.html for the `CEF API`.

**Comment by amaitland** [comment]
> Returns false if cookies cannot be accessed. 

It's not clear the changes your proposing adequately express that cookies cannot be accessed.

> The methods of this class may be called on any thread unless otherwise indicated.

http://magpcss.org/ceforum/apidocs3/projects/(default)/CefCookieManager.html
Reading the `CEF API` again, I'm not sure it's threading related.

**Comment by amaitland** [comment]
Closing this as  #1928 should now be resolved. Thanks for making an attempt, future contributions welcome 👍

**Pull request closed without merging**
