### PR TITLE
Implement Change Preferences at Runtime.

### PR DESCRIPTION
**Pull request by amaitland**
Add new Get/Set preference methods to the RequestContext
Implementation is not quite complete yet.

### CODE REVIEW

**Comment by Bodekaer** [comment]
@myrnazhou FYI a way for us to change spelling on the fly in the near future.

**Comment by myrnazhou** [comment]
@Bodekaer cool (y)

**Comment by amaitland** [comment]
Basic implementation should be complete.

@Bodekaer @myrnazhou If either if you have time to take this for a spin that would be greatly appreciated :+1:

**Comment by amaitland** [comment]
It's probably worth creating an `IRequestContext` interface, so it's easy to write some extension methods in `C#` as I'm sure there will be some common use cases.

**Comment by midas643** [comment]
GetAllPreferences returns null.

var requestContext = new RequestContext(new RequestContextSettings(){CachePath = "data"});
var preferences = requestContext.GetAllPreferences(true);
foreach(var preference in preferences)
{
    //if(preference.Value!= null)
        Debug.Print(preference.Key + " : " + preference.Value);
}

**Comment by amaitland** [comment]
> GetAllPreferences returns null. I'd test if GetPreference/SetPreference works but I don't know preference names. Hmm maybe I use it wrong?

From what I can gather you have to wait for the browser to have initialized before you can call `GetAllPreferences`. 

> Also don't forget to wrap GetDefaultCookieManager :)

@midas643 I don't have any more time to work on this as the moment. Please submit a `PR` if you have time :+1:

**Comment by midas643** [comment]
@amaitland Thanks so much. I've used GetAllPreferences after initialisation and it works.

Output:
apps
browser
content_settings_window
disable_3d_apis
enable_a_ping
enable_do_not_track
enable_referrers
extensions
fullscreen
intl
media
native_messaging
partition
plugins
printing
profile
proxy
settings
spellcheck
webkit
webrtc

**Comment by amaitland** [comment]
@midas643 Excellent news :+1: Any luck with setting a preference? 

Anyone have a suggestion on how to wrap things in a nicer way?

**Comment by amaitland** [comment]
I've rebased this `PR` on `master` and pushed a new commit, `CookieManager` is now exposed, I've also added a `IRequestContext` interface which means you can get access to the `RequestContext` through `IBrowserHost`.

Merging this into `master` now, any `bugs/examples/improvements` can be made in a subsequent `PR`.

**Pull request merged**
