### PR TITLE
Fixed NullReferenceException in DoClose

### LINKED ISSUE #1960: NullReferenceException in CefSharpBrowserWrapper.get_IsPopup()
- **What version of the product are you using?**
    - 55.0.0 Nuget

- **What architecture x86 or x64?**
   - x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    - We have custom implementation of ILifeSpanHandler to make sure popups are opened inside the main window. The implementation of DoClose method I took from WinForms.Example:
```
        public bool DoClose(IWebBrowser browserControl, IBrowser browser)
        {
            //We need to allow popups to close
            //If the browser has been disposed then we'll just let the default behaviour take place
            if (browser.IsDisposed || browser.IsPopup)
            {
                return false;
            }

            //The default CEF behaviour (return false) will send a OS close notification (e.g. WM_CLOSE).
            //See the doc for this method for full details.
            //return true here to handle closing yourself (no WM_CLOSE will be sent).
            return true;
        }
```

Now we are getting the following exception, when users are closing the browser window:
```
Exception Info: System.NullReferenceException
   at CefSharp.Internals.CefSharpBrowserWrapper.get_IsPopup()
   at Invenias.WebControl.Handlers.InveniasLifeSpanHandler.DoClose(CefSharp.IWebBrowser, CefSharp.IBrowser)
   at <Module>.CefSharp.Internals.ClientAdapter.DoClose(CefSharp.Internals.ClientAdapter*, CefRefPtr<CefBrowser>*)
```
 It is definitely something that is time dependant as I was't able to reproduce it consistently. It looks like the code checks that browser is disposed finds that it is not and goes ahead to check whether it's a popup. But meanwhile the browser gets disposed and therefore the errors is thrown. Is that possible?

### PR DESCRIPTION
**Pull request by merceyz**
Resolves #1960

- Fixed the NullReferenceException specified in the issue

### CODE REVIEW

**Comment by merceyz** [comment]
@amaitland Anything I should change for this to be a part of 57?

**Comment by amaitland** [comment]
Sorry, I meant to get around to this one. Code can be simplified to look something like below: 

```c#
bool ClientAdapter::DoClose(CefRefPtr<CefBrowser> browser)
{
	auto handler = _browserControl->LifeSpanHandler;

	if (handler != nullptr)
	{
		//By this point it's possible IBrowser references have been disposed
		//Rather than attempting to rework the rather complex closing logic
		//It's easier to pass in a new wrapper and dispose it straight away
		CefSharpBrowserWrapper browserWrapper(browser);

		handler->DoClose(_browserControl, %browserWrapper);
	}

	return false;
}
```

**Comment by merceyz** [comment]
> Sorry, I meant to get around to this one

No worries, take your time

**Comment by amaitland** [comment]
Thanks for the update 👍

**Comment by amaitland** [comment]
Merged into `cefsharp/57` with https://github.com/cefsharp/CefSharp/commit/325ec0f3cf55c18be39096ddecbd419df33ce127

**Pull request merged**
