### PR TITLE
Add ChromeWidgetMessageInterceptor to WinForms Example

### PR DESCRIPTION
**Pull request by jankurianski**
Addresses #570

### CODE REVIEW

**Comment by jankurianski** [comment]
Anyone have corrections or thoughts before I merge this?

**Comment by amaitland** [comment]
Only question I have is would it be better to explicitly release the handle?

**Comment by amaitland** [comment]
If it's working then I'm happy to merge is as, few formatting things, they can be sorted later :+1:

**Comment by jankurianski** [comment]
> Only question I have is would it be better to explicitly release the handle?

It is working without releasing the handle, but it may be inadvertently preventing garbage collection.  So I have made it explicitly release the handle now.

**Comment by jankurianski** [comment]
> Add browser.HandleDestroyed -= BrowserHandleDestroyed;?

Good catch :+1:

**Comment by amaitland** [comment]
Might be worth adding the extra example from https://github.com/cefsharp/CefSharp/issues/1098#issuecomment-118208651

Can be commented out, just as a user reference?

**Comment by jankurianski** [comment]
> Might be worth adding the extra example from #1098 (comment)
> 
> Can be commented out, just as a user reference?

Good thinking.  I might actually change the `ChromeWidgetMessageInterceptor` to accept an `Action<Message>` delegate, then it can be up to the caller to do what they wish with the widget messages.

**Comment by jankurianski** [comment]
I added a comment about mouse events.

I also moved moved the `ToolStrip`-closing logic into `BrowserTabUserControl`.  Any thoughts?

**Comment by amaitland** [comment]
Looks fine :+1:

**Pull request merged**
