### PR TITLE
High Dpi again

### PR DESCRIPTION
**Pull request by bjarteskogoy**
As far as I can see it works. I'll do some testing with this on our alpha release channel and see what happens.

### CODE REVIEW

**Comment by amaitland** [comment]
Did you end up looking through the updated `cefclient` example?

https://bitbucket.org/chromiumembedded/cef/commits/c27da0e7b120704fe2480aec7bfb624fe52ebda3

**Comment by bjarteskogoy** [comment]
I did some weeks ago, but had forgotten about it ... Thank's for reminding me :) Basically the same things we're doing, so the result is the same, I believe. I can change things a bit, so that method and terminology matches the cef sample.

**Comment by amaitland** [comment]
> I can change things a bit, so that method and terminology matches the cef sample.

Do you think it's worth the effort? If you think there are some long term benefits then sure.

Few formatting issues, spaces vs tabs. Other than that it looks solid :+1:

**Comment by bjarteskogoy** [comment]
Then we'll leave things as they are :) If it works, it works. We're running this code (on master) on our Alpha release. Seems to be working. We're also using quite a bit of Javascript interaction, but everything seems good this far.

**Comment by bjarteskogoy** [comment]
I've just discovered that there is a bug calculating mouse positions. Seems like we're sending device coordinates to Cef. When using the WritableBitmap with correct dpi all coordinates and sizes should be logical sizes. I'll fix that.

**Comment by amaitland** [comment]
> When using the WritableBitmap with correct dpi all coordinates and sizes should be logical sizes. I'll fix that.

I had a quick look at the `cefclient` source, do we need to scale the `drag` coordinates also? (I would assume we need to, haven't looked into it though)

**Comment by bjarteskogoy** [comment]
Are you talking about drag for selecting content, or drag/drop? Mouse drag for selection of content seems to be working correctly with this code.

**Comment by amaitland** [comment]
> Are you talking about drag for selecting content, or drag/drop? Mouse drag for selection of content seems to be working correctly with this code.

There's #1210 also

**Comment by bjarteskogoy** [comment]
I think the idea is that cef offscreen uses https://github.com/cefsharp/CefSharp/pull/1207/files#diff-bfec65df46ec49f4ed79472147689599L1201 to calculate mouse positions. If so maybe it should just work.

**Comment by mmamone** [comment]
I just merged your patch into mine, and everything seems to be fine (there's no adorner layer, so oddities with dragging won't be obvious).
The only thing I noticed, is that while there is text selection, you can see the single pixel borders around the HTML elements. I've attached a pic.
cefsharp-highdpi

**Comment by amaitland** [comment]
> The only thing I noticed, is that while there is text selection, you can see the single pixel borders around the HTML elements. I've attached a pic.

Does this differ to the `cefclient` example in `offscreen rendering mode`?

@bjarteskogoy I see you've pushed a more commits. Are there any other scenarios that need to be tested before merging this?

**Comment by mmamone** [comment]
Mea-culpa - same in the cefclient example.
Didn't realise there was a 1291 build.

**Comment by bjarteskogoy** [comment]
My last commit fixed placement and size of popups. Tested with http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select.

**Pull request merged**
