### PR TITLE
Update to M93

### PR DESCRIPTION
**Pull request by amaitland**
**Issues:** 
- #3636
- #3780

**Summary:** 

CEF Now Requires `VS2019` to build the wrapper, there are also changes required as the headers have been upgraded.

**Changes:** [specify the structures changed] 
- Build `.Net 4.5.2` projects using `VS2019`
- Implement custom reference counting as `VC++` doesn't like using `atomic`
- `Widewine` is now downloaded automatically and the methods to load it manually have been removed (#3767)
      
**How Has This Been Tested?**  
Unit tests pass though only for `.Net 4.5.2` projects as the `Net Core/Net 5` projects aren't building yet.

**Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated documentation

**Checklist:**

- [ ] Tested the code(if applicable)
- [x] Commented my code
- [x] Changed the documentation(if applicable)
- [x] New files have a license disclaimer
- [x] The formatting is consistent with the project (project supports .editorconfig)

TODO:
- [ ] `AppVeyor` currently isn't building both solutions

### CODE REVIEW

**Comment by campersau** [comment]
It seems that the tests are hanging, switching to `dotnet test` also for the netframework version seems to work. (I had the same issue with netcore last year see #3214)

See https://ci.appveyor.com/project/campersau/cefsharp/builds/40570216 and commit https://github.com/campersau/CefSharp/commit/c2295278920f8f299081cea7f02684c93ee1ccb6 which also includes a working matrix build for both solutions. (I disabled the `deploy` as I haven't configured it on my appveyor.)

**Comment by amaitland** [comment]
Thanks. I was thinking we could probably use less resources and build both together. 

Will keep this as a plan B. 

I'll switch to dotnet test and see how that goes.

**Comment by campersau** [comment]
Building both at once also works with a little fix see https://ci.appveyor.com/project/campersau/cefsharp/builds/40586025 and https://github.com/campersau/CefSharp/commit/43d67ab7bc602084b18a4d9040067998a9f9cc82

**Comment by amaitland** [comment]
Thanks, very helpful.

**Pull request merged**
