### PR TITLE
Don't change the .Address property when (among other things) you display...

### PR DESCRIPTION
**Pull request by rassilon**
... DevTools.

Ought to be pretty straightforward.

I wasn't sure if just checking IsPopup was good enough.

The existing test wasn't good enough because DevTools is the main frame for the popup DevTools browser. 

Bill

### CODE REVIEW

**Comment by amaitland** [comment]
I would have though `!browser->IsPopup()` would have done the trick. Did it not resolve the issue?

**Comment by rassilon** [comment]
IsPopup did indeed work just fine apparently.

**Comment by amaitland** [comment]
Still need the main frame check I believe. Otherwise ifames etc will change the url also.

**Comment by amaitland** [comment]
Looks like the frame check isn't required anymore :+1: From memory it was added for a reason, just can't remember what for. Also possible the behavior of `CEF` has changed. `CEF` usually only passes in a frame object when it's relevant. I tested with regular frames and iframes, and it doesn't seem to be called multiple times anymore. So let's ignore my previous comment.

**Comment by rassilon** [comment]
Cool. Thank's for checking.

**Pull request merged**
