### PR TITLE
Update cef.sdk.profs import to use SolutionDir

### PR DESCRIPTION
**Pull request by Haraguroicha**
let cef.sdk reference from SolutionDir\packages not project relative parent

### CODE REVIEW

**Comment by amaitland** [comment]
In what case were you experiencing a problem?

**Comment by amaitland** [comment]
Also can you include a detailed description of the problem this PR solves? In which scenario is the proposed change required?

**Comment by Haraguroicha** [comment]
When I add CefSharp as a submodule, the `packages` folder is not relative parent to `CefSharp.Core` and `CefSharp.BrowserSubprocess.Core`, `packages` is always relative with `$(SolutionDir)\packages`

**Comment by amaitland** [comment]
> When I add CefSharp as a submodule, the packages folder is not relative parent to CefSharp.Core and CefSharp.BrowserSubprocess.Core, packages is always relative with $(SolutionDir)\packages

As a submodule to what exactly? Whilst I'm not against the change, it's just an odd one to be making in the context of the `CefSharp` codebase.

**Comment by Haraguroicha** [comment]
> As a submodule to what exactly?

Sorry for my bad explanation!

I'm create a project and references to `CefSharp`, `CefSharp.BrowserSubprocess`, `CefSharp.BrowserSubprocess.Core`, `CefSharp.Core`, `CefSharp.WinForm` to build a experimental application, but `CefSharp` was add as a submodule in my repository, so directory will be like this:

```
MyProject Solution Repo
|- MyProject
  |- MyProject.csproj
  |- ...
|- CefSharp
  |- CefSharp3.sln
  |- CefSharp.Core
    |- CefSharp.Core.vcxproj
    |- ...
  |- ...
|- packages
|- MyProject.sln
```

Then it will happened an exception when build, because `CefSharp.Core.vcxproj` is reference `cef.sdk` to `$(SolutionDir)\CefSharp\packages` not `$(SolutionDir)\packages`, so try `$(SolutionDir)\packages` instead of `..\packages` will be better.

**Comment by amaitland** [comment]
Fair enough. I'd generally recommend that people use the official `Nuget` packages or generate their own `nuget` packages using the build script unless they're trying to debug a specific problem with `CefSharp`.

**Comment by amaitland** [comment]
Having just upgraded the `cef.sdk` packages, it appears that `Nuget` defaults back to using the relative path, so this change may be overwritten if care isn't taken when upgrading to newer versions.

**Pull request merged**
