### PR TITLE
Updated funding source information for new GH sponsors. Removed a project link that is dead.

### PR DESCRIPTION
**Pull request by mitchcapper**
Not sure you want to remove the other options to really funnel it all to GH or not, but if not this at least prioritized GH.

Dislike doing two items in one merge but as they would likely conflict if they were submitted at the same time and it is just removing a sample project from the readme it's your call.  I couldn't find any new home for the HTMLView project.

### CODE REVIEW

**Comment by amaitland** [comment]
Thanks, I'd totally forgotten about the link in the `Readme`.

**Comment by amaitland** [comment]
> I couldn't find any new home for the HTMLView project.

Does look like it's disappeared, we could link to [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=RamonFMendes.HtmlView), if the project is dead then maybe not much point though.

**Comment by Geevo** [comment]
> > I couldn't find any new home for the HTMLView project.
> 
> Does look like it's disappeared, we could link to [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=RamonFMendes.HtmlView), if the project is dead then maybe not much point though.

A bit of digging and looks as though its been moved it to their personal repo.

[https://github.com/ramon-mendes/HtmlView](https://github.com/ramon-mendes/HtmlView)

**Comment by mitchcapper** [comment]
Nice find!  I tried finding it I guess HTMLView was too generic and google indexing of GH wasn't good enough to find it + vs for me.

**Comment by mitchcapper** [comment]
I  can update this PR adding it back in @amaitland do you want the other funding sources still listed?  Just GH + paypal? Just GH?

**Comment by amaitland** [comment]
> Just GH + paypal?

@mitchcapper Was just going with those two for now, thanks 👍

**Pull request merged**
