### PR TITLE
Add in file paths data to DragData

### PR DESCRIPTION
**Pull request by mbragg12**
See master version of PR.
https://github.com/cefsharp/CefSharp/pull/4649

### CODE REVIEW

**Comment by amaitland** [comment]
As Chromium is now stable at 120 and CEF finally has stable builds available I wasn't planning on releasing another 119 built at this point.

Let me know if you'd still like this merged.

**Comment by mbragg12** [comment]
We are patching it locally so we don’t need it. Mostly put up the PR in case someone else needed it.  I’ll leave it till 120 is released and then close it.

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/releases/tag/v120.1.80 was released a few days ago and includes the new `IDragData.FilePaths` property 👍

**Comment by mbragg12** [comment]
120 released. No longer needed.

**Pull request closed without merging**
