### PR TITLE
Expose Cross-Origin Whitelist from Cef.XXX as static methods.

### PR DESCRIPTION
**Pull request by rassilon**
Custom schemes are much easier to deal with if you can use XHR with them, so on the theory that these APIs work, expose them from CefSharp.

See CEF issues 246 and 950 for more details.

Let me know if these methods should go somewhere else.

Fyi,
Bill

### CODE REVIEW

**Comment by amaitland** [comment]
Few changes required before merging this one

- Add xml documentation
- Rename variables to be camcelCase without underscores

**Comment by rassilon** [comment]
Done. If this could be part of the -pre03 on Nuget that'd be very cool. It's so much easier to build my project with it that way. :)

Bill

**Comment by amaitland** [comment]
> Done. If this could be part of the -pre03 on Nuget that'd be very cool. It's so much easier to build my project with it that way. :)

Thanks! More than happy for this to be in `-pre03` :+1:

**Comment by amaitland** [comment]
`-pre03` is on `nuget`

**Pull request merged**
