### PR TITLE
Fixed LoadHtml loading the Url even if RegisterHandler returns false

### PR DESCRIPTION
**Pull request by merceyz**

### CODE REVIEW

**Comment by amaitland** [comment]
`merged` 👍 Please add a description next time, thanks.

**Comment by merceyz** [comment]
I didn't do it because the explanation fit into the summary, sorry.

**Comment by amaitland** [comment]
No big deal, just a very long description in the changelog (sometimes they have to be long)

**Comment by merceyz** [comment]
Just for a future reference, how detailed do you want it to be?

**Comment by amaitland** [comment]
> Just for a future reference, how detailed do you want it to be?

Be pragmatic about it, just enough detail so that an outside could read the description and understand what the intent of the `PR` is/was.

**Pull request merged**
