### PR TITLE
Reorder dispose pattern in ChromiumWebBrowser

### PR DESCRIPTION
**Pull request by amaitland**
WinForms/Wpf/OffScreen - Reorder Dispose methods
- Set browser initialized to false
- Release event handlers
- Dispose managedCefBrowserAdapter
- Set handlers to null

Follow up to #2651

### CODE REVIEW

**Comment by amaitland** [comment]
All three controls should be roughly the same in order now. Releasing the event handlers before `Disposing` of `ManagedCefBrowserAdapter` should keep the events from being fired mid `Dispose`.

I'm also considering freeing the handlers earlier and just setting `ILifeSpanHandler = null` after  `ManagedCefBrowserAdapter.Dispose`

**Comment by merceyz** [comment]
> I'm also considering freeing the handlers earlier and just setting ILifeSpanHandler = null after ManagedCefBrowserAdapter.Dispose

Is it an option to set all handlers to null before that call, then have it handle the logic of closing the browser further down the stack?

**Comment by amaitland** [comment]
> Is it an option to set all handlers to null before that call

All handlers except `LifeSpanHandler`. It has to be freed after otherwise `LifeSpanHandler.DoClose` won't be called. See https://github.com/cefsharp/CefSharp/blob/cefsharp/71/CefSharp.Wpf/ChromiumWebBrowser.cs#L642

**Comment by amaitland** [comment]
`LifeSpanHandler` is now set to `null` independently of the other handlers which are set to `null` after the event handlers.

**Pull request merged**
