### PR TITLE
Refactoring - Move CefNavigationEntry conversion to TypeConversion

### PR DESCRIPTION
**Pull request by merceyz**
- Moved conversion of `CefNavigationEntry` -> `NavigationEntry` to `CefSharp.Core\Internals\TypeConversion.h`

The conversion of `CefNavigationEntry` -> `NavigationEntry` was duplicated in
- CefSharp.Core\Internals\CefNavigationEntryVisitorAdapter.h
- CefSharp.Core\Internals\CefBrowserHostWrapper.cpp

### CODE REVIEW

**Comment by amaitland** [comment]
Thanks 👍 Will need to take this for a spin before merging as the code was restructured. A quick glance and it looks fine.

**Comment by amaitland** [comment]
I rebased this locally which `GitHub` didn't seem to recognise, so effectively this was merged in https://github.com/cefsharp/CefSharp/commit/58e8a29c77d077defa21ffae6b3edbd761bd9442

Added additional `null` check in https://github.com/cefsharp/CefSharp/commit/1a2d4a82f1532a2d309fcec6c2b384ca385d5c1f and improved xml doc slightly for `SslStatus.CertStatus`

**Comment by merceyz** [comment]
> I rebased this locally which GitHub didn't seem to recognise

To edit this PR so that GitHub notices it, you'd have to get my fork and push to the branch this PR is pointed to

**Comment by amaitland** [comment]
I know, I was trying to be lazy 😄

**Pull request merged**
