### PR TITLE
Async SetCookie

### PR DESCRIPTION
**Pull request by amaitland**
Create wrapper class to call `SetCookie` async using new Task factory.

### CODE REVIEW

**Comment by amaitland** [comment]
Disclaimer I haven't actually tried to run this yet, it builds. Just toying with an idea.

**Comment by amaitland** [comment]
@rassilon What about something like this to make `SetCookie` use the new `TaskFactory`? It's a little crude, though have to work with what we've got I suppose.

Probably need to come up with a better name than `SetCookieInvoker` and it should be in the `Internals` folder.

**Comment by rassilon** [comment]
Oh, I wouldn't have made it a separate class. If I were to do the work I would have just pushed the argument conversions down into IOT_SetCookie.

And, if we wanted to propagate .Net exceptions inside of IOT_SetCookie we would rethrow them after the `->Wait()` && `->IsFaulted` is `TRUE`.

**Comment by rassilon** [comment]
However, the general idea of creating some kind of .Net class to bridge the gap ought to work and we should strive to do that for complicated cases. 

I think the only reason for IOT_SetCookie to have an Invoker class like you did here is if it exceeds the Func/Action generic parameter count limits.

**Comment by amaitland** [comment]
> Oh, I wouldn't have made it a separate class.

I think it makes the code nicer to read :smile: Overhead of a new class is minimal.

**Comment by rassilon** [comment]
It is minimal, the pattern is just a pain to replicate is all. :smile:

**Comment by amaitland** [comment]
It took like `2mins` :stuck_out_tongue_winking_eye: to create the class!

**Comment by amaitland** [comment]
Renamed class and now wraps both Set and Delete.

I think it's an improvement for now. We can revisit later of a preferable pattern is established. Thoughts?

**Comment by rassilon** [comment]
Looks fine to me.

**Pull request merged**
